### ISSUE TITLE
crash on drift continuous model type polynomial

### ISSUE THREAD

**Issue by marcianito** [jkennedy-usgs/sgp-gsadjust#134]
## reproduce error

1. Load CG6 survey data with only one station repeat within survey
2. in Drift tab choose "continuous model"
3. for model type chose any "polynomial" degree

## error

```
/home/mreich/Documents/software/GravityPrograms/sgp-gsadjust/gsadjust/gui/tabs/drift.py:674: MatplotlibDeprecationWarning: Setting the line's pick radius via set_picker is deprecated since 3.3 and will be removed two minor releases later; use set_pickradius instead.
  a = self.axes_drift_cont_upper.plot(x, y, ".-", picker=5)
/home/mreich/Documents/software/GravityPrograms/sgp-gsadjust/gsadjust/gui/tabs/drift.py:687: MatplotlibDeprecationWarning: Setting the line's pick radius via set_picker is deprecated since 3.3 and will be removed two minor releases later; use set_pickradius instead.
  self.axes_drift_cont_lower.plot(
/home/mreich/.pyenv/versions/gsadjust/lib/python3.8/site-packages/numpy/lib/polynomial.py:628: RuntimeWarning: invalid value encountered in true_divide
  lhs /= scale
Traceback (most recent call last):
  File "/home/mreich/Documents/software/GravityPrograms/sgp-gsadjust/gsadjust/gui/tabs/drift.py", line 1217, in drift_combobox_updated
    self.parent.update_drift_tables_and_plots()
  File "/home/mreich/Documents/software/GravityPrograms/sgp-gsadjust/gsadjust/GSadjust.py", line 1329, in update_drift_tables_and_plots
    self.tab_drift.set_drift_method(update, update_adjust_tables)
  File "/home/mreich/Documents/software/GravityPrograms/sgp-gsadjust/gsadjust/gui/tabs/drift.py", line 951, in set_drift_method
    model = self.plot_drift(update=update)
  File "/home/mreich/Documents/software/GravityPrograms/sgp-gsadjust/gsadjust/gui/tabs/drift.py", line 717, in plot_drift
    deltas, xp, yp, z = drift_continuous(
  File "/home/mreich/Documents/software/GravityPrograms/sgp-gsadjust/gsadjust/drift/continuous.py", line 170, in drift_continuous
    z_main = np.polyfit(x0, drift_rate, method_key - 1)
  File "<__array_function__ internals>", line 5, in polyfit
  File "/home/mreich/.pyenv/versions/gsadjust/lib/python3.8/site-packages/numpy/lib/polynomial.py", line 629, in polyfit
    c, resids, rank, s = lstsq(lhs, rhs, rcond)
  File "<__array_function__ internals>", line 5, in lstsq
  File "/home/mreich/.pyenv/versions/gsadjust/lib/python3.8/site-packages/numpy/linalg/linalg.py", line 2306, in lstsq
    x, resids, rank, s = gufunc(a, b, rcond, signature=signature, extobj=extobj)
ValueError: On entry to DLASCL parameter number 4 had an illegal value
/home/mreich/bin/gsadjust: line 13: 130797 Aborted 
```

## suggestion

Even though this might make sense mathematically, I guess this possible "bad-selection" should not let the program crash [happens in both windows and linux], but rather catch the error and give a feedback to the user.

**Comment by jkennedy-usgs** [comment]
Thanks @marcianito! You're right, it doesn't make sense mathematically (trying to fit a curve to a single point) but it also shouldn't crash the program.

I'm working on a v 2.0 release and will include a fix.

To be honest, I rarely use the "continuous" drift correction, even though I think it most closely models gravimeter behavior. The "Roman" method seems to be the best all-around method that doesn't require much thought by the person doing the processing.
