### ISSUE TITLE
program crashed on "write adjustment summary"

### ISSUE THREAD

**Issue by marcianito** [jkennedy-usgs/sgp-gsadjust#96]
When selecting "write adjustment summary", the progam crashed althought the summary is still written correctly.

This is the error shown in commandline:

`Traceback (most recent call last):
  File "gsadjust/GSadjust.py", line 2009, in write_summary_text
    fn = export_summary(self.obsTreeModel, self.settings.value('current_dir'))
  File "/home/mreich/Documents/software/GravityPrograms/sgp-gsadjust/gsadjust/data_export.py", line 153, in export_summary
    for delta in loop.deltas():
  File "/home/mreich/Documents/software/GravityPrograms/sgp-gsadjust/gsadjust/pyqt_models.py", line 549, in deltas
    for i in range(table.rowCount()):
AttributeError: 'NoneType' object has no attribute 'rowCount'
Aborted (core dumped)`

**Comment by jkennedy-usgs** [comment]
Fixed in jk-performance branch, test added.
