### ISSUE TITLE
crash on selecting "auto uncheck sd >" (DataTab)

### ISSUE THREAD

**Issue by marcianito** [jkennedy-usgs/sgp-gsadjust#97]
When selecting a value to uncheck all surveys / data with standard deviation > X, the program crashes, showing the following errors:

`Traceback (most recent call last):
  File "/home/mreich/Documents/software/GravityPrograms/sgp-gsadjust/gsadjust/tab_data.py", line 91, in <lambda>
    autoselec_sd.button.clicked.connect(lambda: self.autoselect_sd(autoselec_sd))
  File "/home/mreich/Documents/software/GravityPrograms/sgp-gsadjust/gsadjust/tab_data.py", line 293, in autoselect_sd
    obstreestation = self.parent.obsTreeModel.itemFromIndex(self.parent.currentStationIndex)
AttributeError: 'MainProg' object has no attribute 'currentStationIndex'
Aborted (core dumped)`

**Comment by jkennedy-usgs** [comment]
Fixed in upcoming v1.0
